[package]
name = "scythe"
version = "0.1.0"
edition = "2021"
authors = ["Berin Aniesh <berinaniesh@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
args = "2.0"
getopts = "0.2"
chess = "3.2.0"
colored = "2.0.0"
